package rules
import com.sbz.itemrecommendationwar.Model.Item;
import com.sbz.itemrecommendationwar.Model.Player;
import com.sbz.itemrecommendationwar.Model.PlayerClass;


rule "Recommend mythic adc item"
agenda-group "mythic"
	when
		$i: Item(playerClass == PlayerClass.MARKSMAN, $i.isMythic == true)
		$p: Player(recommendedItems.empty != true, playerClass == PlayerClass.MARKSMAN, $p.itemIsNotRecommended($i.getName()) == true)
	then 
		
 		modify ($p) {addRecommendedItem($i)};
end