package rules
import com.sbz.itemrecommendationwar.Model.Item;
import com.sbz.itemrecommendationwar.Model.Player;
import com.sbz.itemrecommendationwar.Model.PlayerClass;

rule "Normal item recommendation start"
agenda-group "normal"
	when 
		$i: Item(playerClass == PlayerClass.MARKSMAN, $i.isMythic() == false)
		$p: Player(recommendedItems.empty != true, playerClass == PlayerClass.MARKSMAN, $p.itemIsNotRecommended($i.getName()) == true)
	then
		
 		modify ($p) {addRecommendedItem($i)};
 end
