package rules
import com.sbz.itemrecommendationwar.Model.Item;
import com.sbz.itemrecommendationwar.Model.Player;
import com.sbz.itemrecommendationwar.Model.PlayerClass;
import java.util.List;

rule "First purchase rule ADC"
agenda-group "first-purchase"
no-loop true
	when 
		$i: Item(playerClass == PlayerClass.MARKSMAN, $i.isMythic() == false)
		$p: Player(recommendedItems.empty != true, playerClass == PlayerClass.MARKSMAN,  $p.itemIsNotRecommended($i.getName()) == true)
		
	then
		
		System.out.println($p.getStatToItemize() + " is the dominant stat");
		System.out.println("Usao je u ovo glupo pravilo");
		System.out.println($i.getName() + " is the recommended item");
 		modify ($p) {addRecommendedItem($i)};
 end
 
 
 rule "Next adc purchase"
 agenda-group "first-purchase"
 	when
 		$p: Player($ri: recommendedItems, playerClass == PlayerClass.MARKSMAN)
 		$i: Item(playerClass == PlayerClass.MARKSMAN, $p.itemIsNotRecommended($i.getName()) == true, $p.statToItemize == $i.dominantStat)
 		then
 		System.out.println($p.getStatToItemize() + " is the stat to itemize");
		System.out.println("PUCA JEr SETER NCE DA GA SEtuJE");
		modify ($p) {addRecommendedItem($i)};
end;
