package rules
import com.sbz.itemrecommendationwar.Model.Item;
import com.sbz.itemrecommendationwar.Model.Player;
import com.sbz.itemrecommendationwar.Model.PlayerClass;
import java.util.List;

rule "First purchase rule ADC"
agenda-group "first-purchase"
no-loop true
	when 
		$i: Item(playerClass == PlayerClass.MARKSMAN, $i.isMythic() == false)
		$p: Player(recommendedItems.empty != true, playerClass == PlayerClass.MARKSMAN,  $p.itemIsNotRecommended($i.getName()) == true)
		
	then
		
		System.out.println($p.getStatToItemize() + " is the dominant stat");
		System.out.println("Usao je u ovo glupo pravilo");
		System.out.println($i.getName() + " is the recommended item");
 		modify ($p) {addRecommendedItem($i)};
 end
 

