package rules
import com.sbz.itemrecommendationwar.Model.Item;
import com.sbz.itemrecommendationwar.Model.Player;
import com.sbz.itemrecommendationwar.Model.PlayerClass;


rule "Starter item tank"
agenda-group "starter"
	when
	    $p: Player( recommendedItems.empty == true, playerClass == PlayerClass.TANK)
		$i: Item( name == "Dorans Shield")
	    
	then
		modify ($p) {addRecommendedItem($i)};
end
		
rule "Starter item marksman"
agenda-group "starter"

	when
	    $p: Player( recommendedItems.empty == true, playerClass == PlayerClass.MARKSMAN)
	    $i: Item( name == "Dorans sword")
	then
		modify ($p) {addRecommendedItem($i)};
		
end



