package rules
import com.sbz.itemrecommendationwar.Model.Item;
import com.sbz.itemrecommendationwar.Model.Player;
import com.sbz.itemrecommendationwar.Model.PlayerClass;


rule "Starter item tank"
	when
	    $p: Player( recommendedItems.empty == true, playerClass == PlayerClass.TANK)
		$i: Item( name == "Dorans Shield")
	    
	then
		System.out.println("Recommending the starter item dorans shield for player" + $p.getPlayerClass()) ;
		modify ($p) {addRecommendedItem($i)};
end
		
rule "Starter item marksman"
	when
	    $p: Player( recommendedItems.empty == true, playerClass == PlayerClass.MARKSMAN)
	    $i: Item( name == "Dorans sword")
	then
		System.out.println("Recommending the starter item dorans sword for player" + $p.getName());
		modify ($p) {addRecommendedItem($i)};
		
end



